function createfigure(X1, Y1, Z1, S1, SolarRatio1)
%CREATEFIGURE(X1, Y1, Z1, S1, SolarRatio1)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  SOLARRATIO1:  scatter3 c

%  Auto-generated by MATLAB on 12-Apr-2026 23:48:21

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,SolarRatio1,'Marker','*');

% Create zlabel
zlabel('Solar Ratio');

% Create ylabel
ylabel('Year');

% Create xlabel
xlabel('Day Of Year');

view(axes1,[-37.5 30]);
grid(axes1,'on');
hold(axes1,'off');
% Create colorbar
colorbar(axes1);

