function [fitresult, gof] = createFit(mydelt, myrelhum, mysolarratio)
%CREATEFIT(MYDELT,MYRELHUM,MYSOLARRATIO)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : mydelt
%      Y Input : myrelhum
%      Z Output: mysolarratio
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Apr-2026 01:00:30


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( mydelt, myrelhum, mysolarratio );

% Set up fittype and options.
ft = fittype( 'a*(1+b*AvgRelHumidity_pct)*(1-exp(-c*delt^n))', 'independent', {'delt', 'AvgRelHumidity_pct'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.964888535199277 0.157613081677548 0.970592781760616 0.957166948242946];

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'untitled fit 1', 'mysolarratio vs. mydelt, myrelhum', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'mydelt', 'Interpreter', 'none' );
ylabel( 'myrelhum', 'Interpreter', 'none' );
zlabel( 'mysolarratio', 'Interpreter', 'none' );
grid on
view( -39.0, 34.0 );


